"""empty message

Revision ID: b25f1baa806c
Revises: c5ee6396436e
Create Date: 2024-03-05 22:16:32.931419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25f1baa806c'
down_revision = 'c5ee6396436e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=26), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_data', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
