"""empty message

Revision ID: c5ee6396436e
Revises: 56440b79c859
Create Date: 2023-12-14 19:50:16.757434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ee6396436e'
down_revision = '56440b79c859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_thumbnail', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_data', schema=None) as batch_op:
        batch_op.drop_column('blog_thumbnail')

    # ### end Alembic commands ###
